"""cafes table

Revision ID: d09d159ec283
Revises: f83be16d8df7
Create Date: 2019-04-13 14:54:18.202770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09d159ec283'
down_revision = 'f83be16d8df7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cafe_name', sa.String(length=64), nullable=True),
    sa.Column('owner_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Numeric(precision=8, asdecimal=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe_cafe_name'), 'cafe', ['cafe_name'], unique=True)
    op.create_index(op.f('ix_cafe_email'), 'cafe', ['email'], unique=True)
    op.create_index(op.f('ix_cafe_owner_name'), 'cafe', ['owner_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cafe_owner_name'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_email'), table_name='cafe')
    op.drop_index(op.f('ix_cafe_cafe_name'), table_name='cafe')
    op.drop_table('cafe')
    # ### end Alembic commands ###
