"""barista table

Revision ID: f83be16d8df7
Revises: 
Create Date: 2019-04-13 14:43:29.684863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83be16d8df7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.Numeric(precision=8, asdecimal=False), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barista_email'), 'barista', ['email'], unique=True)
    op.create_index(op.f('ix_barista_name'), 'barista', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_barista_name'), table_name='barista')
    op.drop_index(op.f('ix_barista_email'), table_name='barista')
    op.drop_table('barista')
    # ### end Alembic commands ###
